server.port=8090
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

management.endpoints.web.exposure.include=metrics,health,prometheus

acquiring-bank.gateway.url=${ACQUIRING_BANK_URL:http://localhost:8080}